(() => {
 const G=window.GRIMSKILL;
 function decorateBag(){const eq=document.querySelector('.equipment-grid');if(eq){const cards=[...eq.querySelectorAll('.equip-slot-card')];['head','body','feet'].forEach((slot,k)=>{const c=cards[k+1];if(!c)return;const gear=G.gear(slot),g=gear?.utilityGem?G.gems[gear.utilityGem]:null;c.querySelector('.utility-slot-row')?.remove();const row=document.createElement('div');row.className=`utility-slot-row ${g?'filled':''}`;row.innerHTML=g?`<span>${g.icon}</span><div><b>${g.name}</b><small>${g.kind==='aura'?'常駐光環':'戰鬥中點擊施放'}</small></div><button data-uout="${slot}">×</button>`:`<span>✧</span><div><b>主動 / 光環孔</b><small>佔用此裝備 1 個技能孔</small></div>`;c.appendChild(row);if(g){const empty=c.querySelector('.gear-socket:not(.filled)');if(empty){empty.classList.add('utility-occupied');empty.innerHTML=`<span>${g.icon}</span><b>${g.kind==='aura'?'光環':'主動'}</b>`}}});document.querySelectorAll('[data-uout]').forEach(b=>b.onclick=()=>{game.unsocketUtilityGem(b.dataset.uout);renderAll();renderBag()})}
  document.querySelectorAll('[data-target-slot]').forEach(b=>{const slot=b.dataset.targetSlot,gear=G.gear(slot);if(slot!=='weapon'&&gear?.utilityGem&&(gear.socketed?.length||0)>=Math.max(0,gear.sockets-1))b.disabled=true});
  const root=$('#bagInventory');if(!root)return;root.querySelector('.utility-gem-group')?.remove();const items=game.inventory.map((x,index)=>({...x,index})).filter(x=>x.kind==='utilityGem');if(!items.length)return;const sec=document.createElement('div');sec.className='item-group utility-gem-group';sec.innerHTML='<h4>主動 / 光環技能石</h4>';for(const inv of items){const g=inv.item,d=document.createElement('div');d.className='bag-card utility-gem-card';const bs=['head','body','feet'].map(slot=>{const gear=G.gear(slot),used=(gear?.socketed?.length||0)+(gear?.utilityGem?1:0),ok=gear&&(gear.utilityGem||used<gear.sockets);return `<button data-uindex="${inv.index}" data-uslot="${slot}" ${ok?'':'disabled'}>${G.labels[slot]}</button>`}).join('');d.innerHTML=`<div class="ico">${g.icon}</div><div><strong>${g.name}</strong><small>${g.kind==='aura'?'光環':'主動'} · ${g.desc}</small><div class="socket-targets">${bs}</div></div>`;sec.appendChild(d)}root.appendChild(sec);root.querySelectorAll('[data-uindex]').forEach(b=>b.onclick=()=>{game.socketUtilityGem(Number(b.dataset.uindex),b.dataset.uslot);renderAll();renderBag()})}
 const oldBag=renderBag;renderBag=function(){oldBag();decorateBag()};
 const oldInv=renderInventory;renderInventory=function(){oldInv();const n=game.inventory.filter(x=>x.kind==='utilityGem').length;if(n)$('#inventory').insertAdjacentHTML('beforeend',`<small class="utility-preview">另有 ${n} 顆主動／光環技能石，打開背包配置。</small>`)};
 G.addBattleUI=()=>{if($('#battleUtilityBar'))return;const s=$('#battleSupports');if(!s)return;const d=document.createElement('div');d.id='battleUtilityBar';d.className='battle-utility-bar';s.parentElement.appendChild(d)};
 G.renderBattleUI=rt=>{G.addBattleUI();const root=$('#battleUtilityBar'),aur=G.utilityGems().filter(x=>x.kind==='aura'),act=G.activeGems();root.innerHTML=`<div class="battle-aura-row">${aur.length?aur.map(g=>`<span class="aura-chip">${g.icon} ${g.name}</span>`).join(''):'<span class="aura-chip muted">沒有光環</span>'}</div><div class="active-skill-row">${act.length?act.map((g,i)=>`<button class="active-skill-btn" data-active-gem="${g.id}"><b>${i+1}</b><span>${g.icon}</span><strong>${g.name}</strong><small>READY</small></button>`).join(''):'<span class="active-empty">裝備主動技能石後，可在戰鬥中點擊施放。</span>'}</div>`;root.querySelectorAll('[data-active-gem]').forEach(b=>b.onclick=()=>G.activate?.(b.dataset.activeGem,rt))};
 G.updateButtons=rt=>document.querySelectorAll('[data-active-gem]').forEach(b=>{const g=G.gems[b.dataset.activeGem],rem=Math.max(0,(rt.cooldowns[g.id]||0)-rt.time);b.disabled=rem>0||rt.finished;b.classList.toggle('cooling',rem>0);b.querySelector('small').textContent=rem>0?`${rem.toFixed(1)}s`:'READY'});
 G.addBattleUI();
})();